import { v4 as uuid } from "uuid";
import {
  women1,
  women2,
  women3,
  women4,
  women6,
  women7,
  men1,
  men2,
  men3,
  men4,
  men5,
  kids1,
  kids2,
  kids6,
  kids9,
  kids11,
} from "../../frontend/assets/index";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Elegant gown style kurti",
    origincalPrice: 600,
    discountPrice: 450,
    categoryName: "Women",
    savePercent: 25,
    tailorName: "Lakshmi",
    image: women1,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Fancy net lengha choli",
    origincalPrice: 600,
    discountPrice: 500,
    categoryName: "Women",
    savePercent: 17,
    tailorName: "Lakshmi",
    image: women2,
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: "Wine red lehenga",
    origincalPrice: 1000,
    discountPrice: 800,
    categoryName: "Women",
    savePercent: 20,
    tailorName: "Lakshmi",
    image: women3,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Fancy net lengha choli",
    origincalPrice: 500,
    discountPrice: 1000,
    categoryName: "Women",
    savePercent: 50,
    tailorName: "Lakshmi",
    image: women4,
    rating: 4.5,
  },

  {
    _id: uuid(),
    title: "Blue Jacquard Gown",
    origincalPrice: 1699,
    discountPrice: 2999,
    categoryName: "Women",
    savePercent: 43,
    tailorName: "Lakshmi",
    image: women6,
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Tapetta Silk Gown",
    origincalPrice: 1399,
    discountPrice: 2399,
    categoryName: "Women",
    tailorName: "Lakshmi",
    savePercent: 41,
    image: women7,
    rating: 4.8,
  },
  {
    _id: uuid(),
    title: "Elegant Men Kurtas",
    origincalPrice: 600,
    discountPrice: 300,
    categoryName: "men",
    tailorName: "Raju",
    savePercent: 50,
    image: men1,
    rating: 3.8,
  },
  {
    _id: uuid(),
    title: "Edinwolf Short Kurta",
    origincalPrice: 800,
    discountPrice: 600,
    categoryName: "men",
    tailorName: "Raju",
    savePercent: 25,
    image: men2,
    rating: 3.5,
  },
  {
    _id: uuid(),
    title: "Ethnic Kurta Set",
    origincalPrice: 1000,
    discountPrice: 600,
    categoryName: "men",
    tailorName: "Raju",
    savePercent: 40,
    image: men3,
    rating: 4.3,
  },
  {
    _id: uuid(),
    title: " Men's Ethnic Kurta Set",
    origincalPrice: 1000,
    discountPrice: 600,
    categoryName: "men",
    tailorName: "Raju",
    savePercent: 40,
    image: men4,
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Solid Dupion Silk Kurta",
    origincalPrice: 465,
    discountPrice: 415,
    categoryName: "men",
    tailorName: "Raju",
    savePercent: 11,
    image: men5,
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Fancy Dress",
    origincalPrice: 1000,
    discountPrice: 750,
    categoryName: "children",
    tailorName: "Rachana",
    savePercent: 25,
    image: kids1,
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Tradintional Dress",
    origincalPrice: 1000,
    discountPrice: 850,
    categoryName: "children",
    tailorName: "Rachana",
    savePercent: 15,
    image: kids6,
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Fancy Dress",
    origincalPrice: 1200,
    discountPrice: 1000,
    categoryName: "children",
    tailorName: "Rachana",
    savePercent: 16,
    image: kids9,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Fancy Dress",
    origincalPrice: 1200,
    discountPrice: 1000,
    categoryName: "children",
    tailorName: "Rachana",
    savePercent: 16,
    image: kids2,
    rating: 4.5,
  },
  {
    _id: uuid(),
    title: "Traditional Dress",
    origincalPrice: 1200,
    discountPrice: 800,
    categoryName: "children",
    tailorName: "Rachana",
    savePercent: 33,
    image: kids11,
    rating: 4,
  },
];
